### ISSUE TITLE
Rename a tab from the date/time?

### ISSUE THREAD

**Issue by edgreenberg** [willylatorre/tabeditor#6]
Sorry to use an issue to ask a question. If this doesn't exist, consider it a feature request. 

(BTW, this is very nice and I'm looking forward to trying it out further.) 

Is there any way to rename the time and date on the tab with some text?  So that I can easily find what I put in?  

Is there any way to search for text across the tabs? ((If I know that I referred to toothpaste somewhere, it'd be nice to search for ti. 

Thanks, 
Ed Greenberg

**Comment by willylatorre** [comment]
Actually it is not possible, but I'll work on it a little bit this week and add it asap!

**Comment by willylatorre** [comment]
@edgreenberg Version 0.2.1 should support tab renaming! 
Sorry for the delay!
